rootProject.name = "SkyExcelNetwork"
include(
    "Trash",
    "PlayerProfile",
    "Menu",
    "MenuSystem"
)
include("CashShop")
include("CashShop")
include("SkyBlock")
include("SkyBlock")
include("SEconomy")
include("SEconomy")
include("Trade")
include("GiftBox")
include("ChatChannel")
include("Cosmetic")
include("Fish")
include("Mileage")
include("LockManager")
include("DailyQuest")
include("TabList")
include("AlphaChest")
include("Eglow")
include("NoMacro")
include("AutoClean")
include("BossBar")
include("BGM")
