messages:

  # /인증 쳤을 때 인증안한 사람한테 보내는 메세지
  noVerifyMessage:
    - ""
    - "强 디스코드 &6연동&f을 하지 않으셨습니다!"
    - "家 가입: https://discord.gg/eHDdk3QaRn"
    - ""

  # /인증 쳤을 때 인증한 사람한테 보내는 메세지
  completeVerifyMessage:
    - ""
    - "架 디스코드 &6연동&f을 이미 하셨습니다!"
    - "家 즐거운 메뚜기팜 하세요!"
    - ""

  # /인증 발급 을 쳤을 때 인증 코드를 이미 발급하였을 때
  alreadyVerifyCode: "&f佳 이미 발급받은 &6코드&f가 있습니다. 해당 &6코드&f가 &c만료&f되면 다시 시도해주세요."

  # 인증코드를 발급 하였을 때
  completeVerifyCode:
    - ""
    - "&f架 &f인증코드가 발급되었습니다! 인증코드: &a%verify_code%"
    - "&f佳 &c%expired_seconds%&f초 이내에 &a입력&f해주세요."
    - ""

  # 인증코드가 만료되었을 때
  expiredVerifyCode: "&f佳 &f발급한 &6인증코드&f가 &c만료&f되었습니다."

  # 이미 인증된 계정일 경우
  already_verify_account: "&f强 &f이미 &6인증된 &a계정&f입니다."

  # 인증을 안했을 때 뜨는 타이틀
  notVerifiedTitle:

    # 미인증시 움직임 방지
    cancelMoveEnable: false

    # 타이틀 활성화
    titleEnable: false

    # 대 제목
    title: "&8[ &6/인증 &8]"

    # 소 제목
    subtitle: "&e인증&f을 해주세요!"

    # 보여지는 애니메이션 시간
    fadein: 1

    # 유지 시간
    stay: 2

    # 없어지는 애니메이션 시간
    fadeout: 1

others:

  # 인증 코드 만료 기간 | 만료 이전 재발급 불가
  verifyCodeExpiredSeconds: 30

  # 콘솔에서 인증 커맨드를 사용할 시
  noConsoleCommand: "&f强 &f이 명령어를 콘솔에서 사용이 &c불가능&f합니다!"

  # 유저가 오피 커맨드를 사용할 경우 (Ex: /인증 리로드)
  opCommand: "&f强 &f이 명령어는 &c오피&f만 &a사용&f이 가능합니다."

  # 콘피그를 리로드 하였을 때
  reloadConfig: "架 &f성공적으로 &7콘피그 및 봇&f을 &a리로드&f하였습니다!"

  # 잘못된 명령어를 사용할 시 (Ex: /인증 TEST)
  wrongCommand: "强 &5잘못&f된 &6명령어&f입니다!"

  # 미인증 알림 타이틀 표시 간격
  notVerifiedTitlePeriodSeconds: 5