# 쓰레기통
trash_bin:
  title: "쓰레기통"
  lines: 3

# 귓속말
whisper:
  message: "家 [%from%] → [%to%] : %message%"

# 도배 방지
no_spam:
  chat:
    coolTick: 5

# 확성기
shout:
  coolTick: 100
  money: 10

# 밭보호
farm_protect:
  enable: true

# Shift + F
shift_f:
  execute:
    - '[player] 메뉴 열기 메인메뉴'
    - '[sound] ENTITY_SHULKER_SHOOT'

# 자동청소
auto_clean:
  period: 1800
  messages:
    20MinRemains: "佳 §620분§f 후에 §c모든 아이템§f이 청소됩니다!"
    10MinRemains: "佳 §610분§f 후에 §c모든 아이템§f이 청소됩니다!"
    5MinRemains: "佳 §65분§f 후에 §c모든 아이템§f이 청소됩니다!"
    1MinRemains: "佳 §660초§f 후에 §c모든 아이템§f이 청소됩니다!"
    30SecRemains: "佳 §630초§f 후에 §c모든 아이템§f이 청소됩니다!"
    10SecRemains: "佳 §610초§f 후에 §c모든 아이템§f이 청소됩니다!"
    5SecRemains: "佳 §65초§f 후에 §c모든 아이템§f이 청소됩니다!"
    4SecRemains: "佳 §64초§f 후에 §c모든 아이템§f이 청소됩니다!"
    3SecRemains: "佳 §63초§f 후에 §c모든 아이템§f이 청소됩니다!"
    2SecRemains: "佳 §62초§f 후에 §c모든 아이템§f이 청소됩니다!"
    1SecRemains: "佳 §61초§f 후에 §c모든 아이템§f이 청소됩니다!"
    removed: "架 §c모든 아이템§f이 청소되었습니다 "