name: SkyExcelNetwork
main: net.skyexcel.server.SkyExcelNetworkMain
author: SkyExcel Team
description: SkyExcel Network Plugin

version: 0.1
api-version: 1.19

#의존성
softdepend:
  - WorldEdit
  - ProtocolLib

depend:
  - HeadDatabase
  - PlaceholderAPI
  - WorldBorderAPI

worlds:
  SkyBlock:
    generator: SkyBlock

commands:
  #AlphaChest
  창고:

  #CashShop
  캐시:
  캐시상점:
    aliases: [ cash ]
    
  #DailyQuest
  일일퀘스트:
    aliases: [ q,ㅋ,dlfdlfznptmxm,znptmxm,퀘스트 ]

  #Menu
  메뉴:
    aliases: [ menu,m,ㅁ ]

  #Mileage
  마일리지:
  마일리지상점:

  #FlyTicket
  플라이:

  #RegionAFK
  잠수:
  잠수상점:

  #Job
  직업:
  물통:

  #ChatChannel
  채팅채널:
    aliases: [ c,ㅊ ]

  #Discord
  인증:
    description: 디스코드 인증 관련 명령어
  인증코드:
    description: 디스코드 인증코드 발급 명령어

  #Fish
  낚시:
  낚시대회:

  #GiftBox
  선물함:
  
  #Items
  아이템:

  #PlayTime
  접속시간:

  #Warp
  워프:
    aliases: [ w,warp ]

  #PlayerProfile
  프로필:
  인기도:

  spawn:
    aliases: [ tmvhs,넴주,스폰 ]

  #SEConomy
  돈:
  상점:

  #SkyBlock
  섬:
    aliases: [ SkyBlock,is,tja ]
  섬어드민:

  #Snowy
  눈:
    aliases: [ snowy ]

  #Trade
  거래:

  #Essentials
  trashbin:
    aliases: [ 쓰레기통, trash ]
  w:
    aliases: [ ㅈ, 귓, 귓말, 귓속말, whisper, msg, tell ]
  shout:
    aliases: [ s, ㄴ, 확성기 ]

  #Cosmetic
  코스튬:
    aliases: [ cosmetic, 치장 ]
  cosmt:
  hat:

  #Etc
  test: