name: SkyExcelNetwork
main: net.skyexcel.server.SkyExcelNetwork
authors: [SkyExcel Team]
description: SkyExcel Network Plugin

version: 0.1
api-version: 1.19

commands:
  쓰레기통:
    usage: /<command>
    description: 쓰레기통
    aliases: [trash]
