####################################################################################################
# +----------------------------------------------------------------------------------------------+ #
# │                                                                                              │ #
# │                                                                                              │ #
# │               ███████╗██╗  ██╗██╗   ██╗███████╗██╗  ██╗ ██████╗███████╗██╗                   │ #
# │               ██╔════╝██║ ██╔╝╚██╗ ██╔╝██╔════╝╚██╗██╔╝██╔════╝██╔════╝██║                   │ #
# │               ███████╗█████╔╝  ╚████╔╝ █████╗   ╚███╔╝ ██║     █████╗  ██║                   │ #
# │               ╚════██║██╔═██╗   ╚██╔╝  ██╔══╝   ██╔██╗ ██║     ██╔══╝  ██║                   │ #
# │               ███████║██║  ██╗   ██║   ███████╗██╔╝ ██╗╚██████╗███████╗███████╗              │ #
# │               ╚══════╝╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═╝  ╚═╝ ╚═════╝╚══════╝╚══════╝              │ #
# │                                                                                              │ #
# │                          ■ WebSite: https://skyexcel.net                                     │ #
# │                          ■ Discord: https://discord.gg/TMaAyJsEnQ                            │ #
# │                          ■ Version: v0.1                                                     │ #
# │                          ■ Authors: @Yooinseo @idkNicks                                      │ #
# │                                                                                              │ #
# │                                                                                              │ #
# │                  ■  Copyright © 2022 SkyExcel Team - All Rights Reserved  ■                  │ #
# │                                                                                              │ #
# +----------------------------------------------------------------------------------------------+ #
####################################################################################################


# +----------------------------------------------------------------------------------------------+ #
# │                                                                                              │ #
# │                                    ■  RankUp Settings  ■                                     │ #
# │                            # The below is settings about RankUP #                            │ #
# │                                                                                              │ #
# +----------------------------------------------------------------------------------------------+ #

rankup_settings:

  # Luckperm 랭크 이름
  default:

    # 다음 랭크
    next: 'rank_1'

    # 승급을 하기 위한 조건
    conditions:

      # 돈
      money: 150000

      # 초 단위
      playtime: 3600
  rank_1:
    next: 'rank_2'
    conditions:
      money: 350000
      playtime: 43200
  rank_2:
    next: 'rank_3'
    conditions:
      money: 700000
      playtime: 86400
  rank_3:
    next: 'rank_4'
    conditions:
      money: 1400000
      playtime: 259200

rankup_other_settings:

  # 최대 랭크
  highestRank: 'rank_4'















