name: SkyBlock
main: net.skyexcel.server.SkyBlockCore
version: 1.0
api-version: 1.13

commands:
  섬:
  섬어드민:
  other:
worlds:
  SkyBlock:
    generator: SkyBlock
softdepend:
  - SkyExcelCore
  - PlaceHolderAPI
  - WorldEdit
  - ProtocolLib