####################################################################################################
# +----------------------------------------------------------------------------------------------+ #
# │                                                                                              │ #
# │                                                                                              │ #
# │               ███████╗██╗  ██╗██╗   ██╗███████╗██╗  ██╗ ██████╗███████╗██╗                   │ #
# │               ██╔════╝██║ ██╔╝╚██╗ ██╔╝██╔════╝╚██╗██╔╝██╔════╝██╔════╝██║                   │ #
# │               ███████╗█████╔╝  ╚████╔╝ █████╗   ╚███╔╝ ██║     █████╗  ██║                   │ #
# │               ╚════██║██╔═██╗   ╚██╔╝  ██╔══╝   ██╔██╗ ██║     ██╔══╝  ██║                   │ #
# │               ███████║██║  ██╗   ██║   ███████╗██╔╝ ██╗╚██████╗███████╗███████╗              │ #
# │               ╚══════╝╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═╝  ╚═╝ ╚═════╝╚══════╝╚══════╝              │ #
# │                                                                                              │ #
# │                          ■ WebSite: https://skyexcel.net                                     │ #
# │                          ■ Discord: https://discord.gg/TMaAyJsEnQ                            │ #
# │                          ■ Version: v0.1                                                     │ #
# │                          ■ Authors: @Yooinseo @idkNicks                                      │ #
# │                                                                                              │ #
# │                                                                                              │ #
# │                  ■  Copyright © 2022 SkyExcel Team - All Rights Reserved  ■                  │ #
# │                                                                                              │ #
# +----------------------------------------------------------------------------------------------+ #
####################################################################################################


# +----------------------------------------------------------------------------------------------+ #
# │                                                                                              │ #
# │                                   ■  Cash Shop Setting  ■                                    │ #
# │                         # Things related to cash shop gui setting #                          │ #
# │                                                                                              │ #
# +----------------------------------------------------------------------------------------------+ #

playerprofile_gui_settings:

  # You can insert the desired TITLE into the GUI
  gui_title: 구매가격/판매가격

  # You can change the GUI to any size.
  gui_size: 27

  gui_settings:
      # You can choose the name you want.
      playerinfo:
        # You can put the item you want in the GUI.
        item: PLAYER_HEAD

        # You can assign the custom model data you want to the item.
        custommodeldata: 2

        # You can specify the display_name of the item.
        display_name: "%player%님의 캐시정보"

        # You can specify the amount of the item.
        amount: 1

        # You can position the item slot in the GUI.
        slot: 10

        # You can change the GUI to the desired lore.
        lore:
          - ""
          - "보유중인 캐시: %my_cash%"
          - "사용한 캐시: %used_cash%"
          - ""
          - "구매한 아이템 갯수: %buyed_item%개"
          - "판매한 아이템 갯수: %selled_item%개"
          - ""

      # When you send cash to the player, if you enter <amount> in the chat, the amount of cash is paid as much as the <amount> value.
      send_cash:

        # You can put the item you want in the GUI.
        item: PLAYER_HEAD

        # Creating a HeadDataBase id will bring up the desired PLAYER_HEAD
        hdb: '21771'

        # You can specify the display_name of the item.
        display_name: "캐시 지급"

        # You can specify the amount of the item.
        amount: 1

        # You can assign the custom model data you want to the item.
        custommodeldata: 2

        # You can position the item slot in the GUI.
        slot: 12

        # You can change the GUI to the desired lore.
        lore:
          - ""
          - "클릭시 플레이어에게 <Amount>의 캐시를 지급합니다."
          - ""

      # When you delete cash to the player, if you enter <amozunt> in the chat, the cash is deleted by the <amount> value.
      remove_cash:

        # You can put the item you want in the GUI.
        item: PLAYER_HEAD

        # Creating a HeadDataBase id will bring up the desired PLAYER_HEAD
        hdb: '9382'

        # You can assign the custom model data you want to the item.
        custommodeldata: 2

        # You can specify the display_name of the item.
        display_name: "캐시 제거"

        # You can specify the amount of the item.
        amount: 1

        # You can position the item slot in the GUI.
        slot: 13

        # You can change the GUI to the desired lore.
        lore:
          - ""
          - "클릭시 플레이어에게 <Amount>의 캐시를 제거합니다."
          - ""

      # When you set cash to the player, if you enter <amount> in the chat, the cash is set by the <amount> value.
      set_cash:

        # You can put the item you want in the GUI.
        item: PLAYER_HEAD

        # Creating a HeadDataBase id will bring up the desired PLAYER_HEAD
        hdb: '9382'

        # You can assign the custom model data you want to the item.
        custommodeldata: 2

        # You can specify the display_name of the item.
        display_name: "캐시 제거"

        # You can specify the amount of the item.
        amount: 1

        # You can position the item slot in the GUI.
        slot: 14

        # You can change the GUI to the desired lore.
        lore:
          - ""
          - "클릭시 플레이어에게 <Amount>의 캐시를 설정합니다."
          - ""

      # When you close the menu
      close_profile:

        # You can put the item you want in the GUI.
        item: BARRIER

        # You can assign the custom model data you want to the item.
        custommodeldata: 2

        # You can specify the display_name of the item.
        display_name: "닫기"

        # You can specify the amount of the item.
        amount: 1

        # You can position the item slot in the GUI.
        slot: 14

        # You can change the GUI to the desired lore.
        lore:
          - ""
          - "클릭시 메뉴를 닫습니다."
          - ""




